# Name of the GitHub Actions workflow
name: CI/CD Pipeline

# Define the events that trigger the workflow
on:
  push: # Trigger on a push event to the main branch
    branches: [ main ]
  pull_request: # Trigger on a pull request targeting the main branch
    branches: [ main ]

# Define the jobs to run as part of the workflow
jobs:
  build-and-test: # Job name
    runs-on: ubuntu-latest # Specify the operating system/environment for the job

    steps: # List of steps to execute within the job
    - name: Checkout code
      uses: actions/checkout@v3 # Check out the repository's code to the workflow runner

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Set up Docker Buildx for building multi-platform images

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3 # Log in to GitHub Container Registry with credentials
      with:
        registry: ghcr.io # Specify the registry to log in to
        username: ${{ github.actor }} # Use the GitHub actor (user) for authentication
        password: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub-provided token for authentication

    - name: Build Docker image
      run: |
        # Build the Docker image with the specified tag
        docker build -t object-detection-api:latest .

    - name: Run tests
      run: |
        # Run tests inside the built Docker container using pytest
        docker run --rm object-detection-api:latest pytest tests

    # Optional: Push the Docker image to GitHub Container Registry
    - name: Tag and push Docker image
      run: |
        # Convert repository name to lowercase for Docker compliance
        IMAGE_ID=ghcr.io/omkar2101/object-detection-api
        docker tag object-detection-api:latest $IMAGE_ID:latest
        # Push the tagged image to the registry
        docker push $IMAGE_ID:latest