name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t object-detection-api:latest .

    - name: Run tests
      run: |
        docker run --rm object-detection-api:latest pytest tests

    Optional: Push image to GHCR
    - name: Tag and push Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}/object-detection-api
        docker tag object-detection-api:latest $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
